apiVersion: v2
name: app-translator
description: Application for translating text with PostgreSQL (Bitnami dependency)
type: application
version: 2.0.0
appVersion: "2.0.0"

maintainers:
  - name: Esti Genauer
    email: genauer1997@gmail.com

dependencies:
  - name: postgresql
    version: "18.5.1"
    repository: https://charts.bitnami.com/bitnami
