apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-translator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/estigenauer/app-translator.git
    targetRevision: main
    path: HelmChartPostgress/my-app/app-translator
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
